apps/domains/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import *

urlpatterns = patterns('apps.domains.views',
    url(regex=r'^$', view='domain_list', name='all'),
    url(regex=r'^add/$', view='domain_ac', name='add_domain'),
    url(regex=r'^(?P<domain_id>\d+)/$', view='domain_ac', name='change_domain'),
    url(regex=r'^(?P<domain_id>\d+)/delete/$', view='domain_delete', name='delete_domain'),
    url(regex=r'^(?P<domain_id>\d+)/dns/$', view='domain_dns', name='dns'),
    url(regex=r'^(?P<domain_id>\d+)/dns/(?P<dns_id>\d+)/$', view='domain_dns_ac', name='change_dns'),
    url(regex=r'^(?P<domain_id>\d+)/dns/add/$', view='domain_dns_ac', name='add_dns'),
    url(regex=r'^(?P<domain_id>\d+)/dns/(?P<dns_id>\d+)/delete/$', view='domain_dns_delete', name='delete_dns'),

)

lesshms/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from libs.bootstrap.forms import BootstrapAuthenticationForm


urlpatterns = patterns('',
    url(r'^$', 'apps.dashboard.views.dashboard', name='dashboard'),
)

# Auth
urlpatterns += patterns('django.contrib.auth.views', url(
    view='login',
    regex=r'^login/$',
    kwargs={
        'template_name': 'registration/login.html',
        'authentication_form': BootstrapAuthenticationForm
    },
    name='login')
)

urlpatterns += patterns('django.contrib.auth.views', url(
    view='logout',
    regex=r'^logout/$',
    kwargs={'next_page': '/'},
    name='logout'
)
)

# Apps
urlpatterns += patterns('',
    (r'^domains/', include('apps.domains.urls', namespace="domains")),
    (r'^projects/', include('apps.projects.urls', namespace="projects")),
    (r'^users/', include('apps.users.urls', namespace="users")),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

apps/domains/models.py
# -*- coding: utf-8 -*-
import os

from django.db import models
from django.db.models.signals import post_delete, post_save
from django.template.loader import render_to_string

from lesshms.paths import BIND
from lesshms.server_conf import NS1, NS2, HOSTNAME, SERVER_IP, HOSTER_NS1, HOSTER_NS2
from apps.domains.signals import change_domain_list
from libs.fields import DomainNameField


class Domain(models.Model):
    name = DomainNameField(u"Domain", max_length=255, help_text=u"example.com", unique=True)
    is_root = models.BooleanField(u"Is root domain", default=False)

    class Meta:
        verbose_name = u"Domain"
        verbose_name_plural = u"Domains"
        ordering = ["name"]

    def __unicode__(self):
        return self.get_normal_name()

    def get_normal_name(self):
        return self.name.decode("idna")

    def get_name_dot(self):
        """
        A dot at the end.
        example.com -> example.com.
        """
        name = self.get_normal_name()

        if not name.endswith("."):
            return u"%s." % name
        return name

    def get_name_without_dot(self):
        """
        A dot at the end.
        example.com.. -> example.com
        """
        name = self.name

        while name.endswith("."):
            name = name[:-1]
        return name

    def init_dns(self):
        """
        Create initial DNS records for domain.
        """

        DNS.objects.filter(domain=self).delete()

        # SOA
        DNS(
            domain=self,
            dns_type="SOA",
            value="%s. root.%s. (2013092600 10800 3600 604800 86400)" % (HOSTNAME, HOSTNAME)
        ).save()

        # NS
        ns1 = HOSTER_NS1 if self.is_root else NS1
        ns2 = HOSTER_NS2 if self.is_root else NS2

        DNS(domain=self, dns_type="NS", sub_domain="%s." % ns1).save()
        DNS(domain=self, dns_type="NS", sub_domain="%s." % ns2).save()

        # MX
        DNS(domain=self, dns_type="MX", priority=10, mx_server="mail").save()
        DNS(domain=self, dns_type="MX", priority=20, mx_server="mail").save()

        DNS(domain=self, dns_type="A", value=SERVER_IP).save()

    def save_dns(self):
        """
        Create DNS file in Bind directory.
        """

        dns = open(os.path.join(BIND, self.get_name_without_dot()), "w+")
        dns_template = render_to_string("domains/conf/dns.html", {
            "domain": self,
            "SERVER_IP": SERVER_IP,
            "dns": self.dns_set.all().order_by("id")
        })
        dns.write(dns_template)

        dns.close()


DNS_TYPES = [
    ["MX", "MX"],
    ["SOA", "SOA"],
    ["NS", "NS"],
    ["A", "A"],
    ["CNAME", "CNAME"]
]


class DNS(models.Model):
    domain = models.ForeignKey(Domain, verbose_name=u"domain", on_delete=models.CASCADE)
    dns_type = models.CharField(u"DNS type", choices=DNS_TYPES, max_length=10, null=False)

    sub_domain = models.CharField(u"sub domain", max_length=100, blank=True)
    mx_server = models.CharField(u"MX server", max_length=100, blank=True)
    priority = models.PositiveIntegerField(u"priority", null=True, default=None)
    value = models.CharField(u"value", blank=True, default="", max_length=100)

    class Meta:
        verbose_name = u"DNS"
        verbose_name_plural = u"DNS"

    def __unicode__(self):
        return u"DNS for %s" % self.domain.name

    def get_domain(self):
        if self.dns_type == "MX":
            if self.sub_domain:
                return self.sub_domain
        return self.domain.get_name_dot()

    def get_value(self):
        if self.dns_type == "MX":
            return "%s %s" % (self.priority, self.mx_server)

        if self.dns_type in ["A", "SOA"]:
            return self.value

        if self.dns_type == "NS":
            return self.sub_domain

        return ""


post_save.connect(change_domain_list, sender=Domain)
post_delete.connect(change_domain_list, sender=Domain)

apps/domains/forms.py
# -*- coding: utf-8 -*-

from django import forms
from libs.validators import DomainNameValidator

# TODO need to create Field and Widget for class=form-control.


class DomainForm(forms.Form):
    name = forms.CharField(
        label=u"Domain name",
        required=True,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "For example, domain.com"
        }),
        validators=[DomainNameValidator]
    )

    is_root = forms.BooleanField(
        label=u"Use Hoster NS",
        required=False,
    )

    def __init__(self, domain_id, *args, **kwargs):
        super(DomainForm, self).__init__(*args, **kwargs)
        self.domain_id = domain_id

    def clean_name(self):
        from apps.domains.models import Domain

        name = self.cleaned_data.get('name').strip().lower()

        # Check unique
        if Domain.objects.filter(name=name).exclude(id=self.domain_id).exists():
            raise forms.ValidationError(u"The domain %s already exists" % name)
        return name


# DNS forms
class MXRecordForm(forms.Form):
    dns_type = forms.CharField(
        widget=forms.HiddenInput()
    )
    priority = forms.IntegerField(
        label=u"Priority",
        required=True,
        # In fact, the value can take 0, but I use PositiveIntegerField:)
        min_value=1,
        max_value=65535,
        widget=forms.TextInput(attrs={
            "class": "form-control"
        }),
    )
    mx_server = forms.CharField(
        label=u"MX server",
        required=True,
        widget=forms.TextInput(attrs={
            "class": "form-control"
        })
    )
    sub_domain = forms.CharField(
        label=u"Subdomain",
        required=True,
        widget=forms.TextInput(attrs={
            "class": "form-control"
        })
    )

apps/domains/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404
from django.template import RequestContext
from django.template.loader import get_template
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib import messages

from apps.domains.models import Domain, DNS
from apps.domains.forms import DomainForm, MXRecordForm


@login_required
def domain_list(request):
    domains = Domain.objects.all()

    template = get_template("domains/domain_list.html")
    context = RequestContext(request, {
        "mm_item": "domains",
        "html_title": u"Domains",
        "domains": domains
    })
    return HttpResponse(template.render(context))


@login_required
def domain_ac(request, domain_id=None):

    domain_dict = None
    if domain_id:
        domain = get_object_or_404(Domain, id=domain_id)
        domain_dict = {
            "name": domain.get_normal_name(),
            "is_root": domain.is_root
        }
    else:
        domain = Domain()

    form = DomainForm(domain_id, request.POST or None, initial=domain_dict, )

    if request.method == "POST":
        if form.is_valid():
            domain.name = form.cleaned_data["name"]
            domain.is_root = form.cleaned_data["is_root"]
            domain.save()

            messages.info(request, 'Domain %s is %s.' % (domain.name, "changed" if domain_id else "added"))

            return HttpResponseRedirect(reverse("domains:all"))

    template = get_template("domains/domain_ac.html")
    context = RequestContext(request, {
        "mm_item": "domains",
        "html_title": u"Add domain" if not domain_id else u"Change domain",

        "breadcrumbs": [
            {"name": u"Domains", "url": reverse("domains:all")},
        ],

        "form": form,
        "change": domain_id
    })
    return HttpResponse(template.render(context))


@login_required
def domain_delete(request, domain_id):
    domain = get_object_or_404(Domain, id=domain_id)
    domain_name = domain.get_normal_name()
    domain.delete()

    messages.info(request, 'Domain %s deleted' % domain_name)

    return HttpResponseRedirect(reverse("domains:all"))


@login_required
def domain_dns(request, domain_id):
    domain = get_object_or_404(Domain, id=domain_id)

    dns = domain.dns_set.all().order_by("id")

    template = get_template("domains/domain_dns.html")
    context = RequestContext(request, {
        "mm_item": "domains",
        "html_title": u"DNS %s" % domain.get_normal_name(),

        "breadcrumbs": [
            {"name": u"Domains", "url": reverse("domains:all")},
            {"name": domain.get_normal_name()},
            {"name": "DNS"},
        ],

        "dns": dns,
        "domain": domain
    })
    return HttpResponse(template.render(context))


@login_required
def domain_dns_ac(request, domain_id, dns_id=None):
    """
    Add/Change DNS Record.
    Only MX record.
    """
    domain = get_object_or_404(Domain, id=domain_id)

    dns_data = {
        "dns_type": "MX"
    }
    if dns_id:
        dns = get_object_or_404(DNS, id=dns_id, domain=domain, dns_type="MX")

        dns_data = {
            "sub_domain": dns.sub_domain or domain.get_name_dot(),
            "mx_server": dns.mx_server,
            "priority": dns.priority,
            "dns_type": dns.dns_type
        }
    else:
        dns = DNS(domain=domain)

    form = MXRecordForm(request.POST or None, initial=dns_data)

    if request.method == "POST":
        if form.is_valid():
            for field in ["sub_domain", "mx_server", "priority", "dns_type"]:
                setattr(dns, field, form.cleaned_data[field])
            dns.save()
            domain.save_dns()

            messages.info(request, 'DNS record %s for domain %s %s' % (
                dns.dns_type,
                domain.get_normal_name(),
                "changed" if dns_id else "added"
            ))

            return HttpResponseRedirect(reverse("domains:dns", kwargs={"domain_id": domain.id}))

    template = get_template("domains/domain_dns_ac.html")
    context = RequestContext(request, {
        "mm_item": "domains",
        "html_title": u"Domain DNS",

        "breadcrumbs": [
            {"name": u"Domains", "url": reverse("domains:all")},
            {"name": domain.get_normal_name()},
            {"name": "DNS", "url": reverse('domains:dns', kwargs={"domain_id": domain.id})}
        ],

        "dns": dns,
        "domain": domain,
        "form": form,
        "change": dns_id
    })
    return HttpResponse(template.render(context))


@login_required
def domain_dns_delete(request, domain_id, dns_id=None):

    domain = get_object_or_404(Domain, id=domain_id)
    dns = get_object_or_404(DNS, id=dns_id, domain=domain, dns_type="MX")
    dns_type = dns.dns_type
    dns.delete()

    messages.info(request, 'DNS record %s for domain %s deleted' % (
        dns_type,
        domain.get_normal_name()
    ))

    return HttpResponseRedirect(reverse("domains:dns", kwargs={"domain_id": domain.id}))

apps/domains/templates/domains/domain_ac.html
{% extends "index.html" %}

{% block application %}
    <h1>{% if change %}Change{% else %}Add{% endif %} domain</h1>

    <form role="form" method="post">
        {% csrf_token %}

        <div class="row">
            <div class="col-lg-6">

                {% include "bootstrap/form_field.html" with field=form.name %}
                {% include "bootstrap/checkbox_form_field.html" with field=form.is_root %}

                <button type="submit" class="btn btn-primary">{% if change %}Change{% else %}Add{% endif %} domain</button>
            </div>
        </div>

    </form>


{% endblock %}

apps/domains/templates/domains/domain_dns.html
{% extends "index.html" %}

{% block application %}
    <div class="page-header">
        <h1>DNS for {{ domain.get_normal_name }} </h1>
    </div>

    <a href="{% url 'domains:add_dns' domain_id=domain.id %}" class="btn btn-primary" style="float: right"><span class="glyphicon glyphicon-plus"></span> Add MX DNS record</a>


    <table class="table table-striped">
        <colgroup>
            <col width="150px"/>
            <col width="100px"/>
            <col/>
            <col width="200px"/>
        </colgroup>
        <thead>
        <tr>
            <th>Domain</th>
            <th>Record</th>
            <th>Value</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for record in dns %}
            <tr>
                <td>
                    {{ record.get_domain }}
                </td>
                <td>
                    IN {{ record.dns_type }}
                </td>
                <td>
                    {{ record.get_value }}
                </td>
                <td style="text-align: right">
                    {% if record.dns_type == "MX" %}
                        <a href="{% url 'domains:change_dns' domain_id=domain.id dns_id=record.id %}" class="btn"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="{% url 'domains:delete_dns' domain_id=domain.id dns_id=record.id %}" class="btn"><span class="glyphicon glyphicon-remove"></span></a>
                    {% else %}
                        <a href="#" class="btn disabled"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="#" class="btn disabled"><span class="glyphicon glyphicon-remove"></span></a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

apps/domains/templates/domains/domain_dns_ac.html
{% extends "index.html" %}

{% block application %}
    <h1>MX record for {{ domain.get_normal_name }}</h1>

    <form role="form" method="post">
        {% csrf_token %}

        {{ form.dns_type }}

        {% include "bootstrap/form_field.html" with field=form.sub_domain %}
        {% include "bootstrap/form_field.html" with field=form.mx_server %}
        {% include "bootstrap/form_field.html" with field=form.priority %}

        <button type="submit" class="btn btn-primary">{% if change %}Change{% else %}Add{% endif %} record</button>

    </form>


{% endblock %}

apps/domains/templates/domains/domain_list.html
{% extends "index.html" %}

{% block application %}
    <div class="page-header">
        <h1>Domains</h1>
    </div>

    {% if domains %}
        <a href="{% url 'domains:add_domain' %}" class="btn btn-primary" style="float: right"><span class="glyphicon glyphicon-plus"></span> Add domain</a>
    {% endif %}

    {% if domains %}
        <table class="table table-striped">
            <colgroup>
                <col width="300px"/>
                <col width="100px"/>
                <col/>
                <col width="200px"/>
            </colgroup>
            <thead>
            <tr>
                <th>Domain name</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for domain in domains %}
                <tr>
                    <td>
                        <a href="{% url 'domains:change_domain' domain_id=domain.id %}">{{ domain.name }}</a>
                    </td>
                    <td>{% if domain.is_root %}<span class="label label-primary">Used Hoster NS</span>{% endif %}</td>
                    <td>
                        {% if domain.name != domain.get_normal_name %}
                            {{ domain.get_normal_name }}
                        {% endif %}
                    </td>
                    <td style="text-align: right">
                        <a href="{% url 'domains:dns' domain_id=domain.id %}" class="btn">DNS</a>
                        <a href="{% url 'domains:change_domain' domain_id=domain.id %}" class="btn"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="{% url 'domains:delete_domain' domain_id=domain.id %}" class="btn"><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <a href="{% url 'domains:add_domain' %}" class="btn btn-primary btn-lg">Add first domain</a>
    {% endif %}

{% endblock %}