apps/domains/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import *

urlpatterns = patterns('apps.domains.views',
    url(regex=r'^$', view='domain_list', name='all'),
    url(regex=r'^add/$', view='domain_ac', name='add_domain'),
    url(regex=r'^(?P<domain_id>\d+)/$', view='domain_ac', name='change_domain'),
    url(regex=r'^(?P<domain_id>\d+)/delete/$', view='domain_delete', name='delete_domain'),
    url(regex=r'^(?P<domain_id>\d+)/dns/$', view='domain_dns', name='dns'),
    url(regex=r'^(?P<domain_id>\d+)/dns/(?P<dns_id>\d+)/$', view='domain_dns_ac', name='change_dns'),
    url(regex=r'^(?P<domain_id>\d+)/dns/add/$', view='domain_dns_ac', name='add_dns'),
    url(regex=r'^(?P<domain_id>\d+)/dns/(?P<dns_id>\d+)/delete/$', view='domain_dns_delete', name='delete_dns'),

)

apps/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import *

urlpatterns = patterns('apps.users.views',
    url(regex=r'^$', view='user_list', name='user_list'),
    url(regex=r'^add/$', view='user_add', name='add_user'),
    #url(regex=r'^(?P<domain_id>\d+)/$', view='domain_ac', name='change_domain'),
    #url(regex=r'^(?P<domain_id>\d+)/delete/$', view='domain_delete', name='delete_domain'),
    #url(regex=r'^(?P<domain_id>\d+)/dns/$', view='domain_dns', name='dns'),
    #url(regex=r'^(?P<domain_id>\d+)/dns/(?P<dns_id>\d+)/$', view='domain_dns_ac', name='change_dns'),
    #url(regex=r'^(?P<domain_id>\d+)/dns/add/$', view='domain_dns_ac', name='add_dns'),
    #url(regex=r'^(?P<domain_id>\d+)/dns/(?P<dns_id>\d+)/delete/$', view='domain_dns_delete', name='delete_dns'),
)

lesshms/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from libs.bootstrap.forms import BootstrapAuthenticationForm


urlpatterns = patterns('',
    url(r'^$', 'apps.dashboard.views.dashboard', name='dashboard'),
)

# Auth
urlpatterns += patterns('django.contrib.auth.views', url(
    view='login',
    regex=r'^login/$',
    kwargs={
        'template_name': 'registration/login.html',
        'authentication_form': BootstrapAuthenticationForm
    },
    name='login')
)

urlpatterns += patterns('django.contrib.auth.views', url(
    view='logout',
    regex=r'^logout/$',
    kwargs={'next_page': '/'},
    name='logout'
)
)

# Apps
urlpatterns += patterns('',
    (r'^domains/', include('apps.domains.urls', namespace="domains")),
    (r'^projects/', include('apps.projects.urls', namespace="projects")),
    (r'^users/', include('apps.users.urls', namespace="users")),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

lesshms/templates/base.html
<!DOCTYPE html>{% load static %}
<html>
<head>
    <title>{% firstof html_title "LessHMS" %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% get_static_prefix %}img/favicon.ico">

    <!-- Bootstrap -->
    <link href="{% get_static_prefix %}css/bootstrap/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{% get_static_prefix %}css/bootstrap/bootstrap-theme.min.css" rel="stylesheet" media="screen">

    <link href="{% get_static_prefix %}css/lesshms.css" rel="stylesheet" media="screen">

    <!--[if lt IE 9]>
      <script src="{% get_static_prefix %}js/vendor/html5shiv.js"></script>
      <script src="{% get_static_prefix %}js/vendor/respond.min.js"></script>
    <![endif]-->

    {% block js %}{% endblock %}

</head>
<body>
{% block base %}{% endblock %}

<script src="{% get_static_prefix %}js/vendor/jquery-1.10.2.min.js"></script>
<script src="{% get_static_prefix %}js/vendor/bootstrap.min.js"></script>
{% block ex_js %}{% endblock %}

<script src="{% get_static_prefix %}js/lesshms_utils.js"></script>
<script src="{% get_static_prefix %}js/lesshms.js"></script>

</body>
</html>

lesshms/templates/breadcrumbs.html
{% if breadcrumbs %}
    <ol class="breadcrumb">
        <li><a href="/">Home</a></li>

        {% for b in breadcrumbs %}

            {% if b.url %}
                <li{% if forloop.last %} class="active"{% endif %}><a href="{{ b.url }}">{{ b.name }}</a></li>
            {% else %}
                <li{% if forloop.last %} class="active"{% endif %}>{{ b.name }}</li>
            {% endif %}

        {% endfor %}

    </ol>
{% endif %}

lesshms/templates/footer.html
<div id="footer">
    <div class="container">
        <p class="text-muted credit">LessHMS {% now "Y" %}. Created by <a href="http://shultais.com">Shultais Group</a></p>
    </div>
</div>

lesshms/templates/index.html
{% extends "base.html" %}

{% block base %}
    <div id="wrap"><!-- #wrap -->
        {% include "main_menu.html" %}

        <div class="container">
            {% include "breadcrumbs.html" %}

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
                        <p>{{ message }}</p>
                    </div>
                {% endfor %}
            {% endif %}

            {% block application %}{% endblock %}
        </div>

        <div style="height: 20px"></div>
    </div><!-- /#wrap -->

    {% include "footer.html" %}
{% endblock %}

lesshms/templates/main_menu.html
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">LessHMS</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li{% if mm_item == 'dashboard' %} class="active"{% endif %}><a href="/"><span class="glyphicon glyphicon-home"></span></a></li>
                <li{% if mm_item == 'domains' %} class="active"{% endif %}><a href="{% url 'domains:all' %}">Domains</a></li>
                <li{% if mm_item == 'users' %} class="active"{% endif %}><a href="{% url 'users:user_list' %}">Users</a></li>
                <li{% if mm_item == 'projects' %} class="active"{% endif %}><a href="{% url 'projects:all' %}">Projects</a></li>
                {% comment %}
                Coming soon
                <li{% if mm_item == 'caches' %} class="active"{% endif %}><a href="#caches">Caches</a></li>
                <li{% if mm_item == 'db' %} class="active"{% endif %}><a href="#db">Data Bases</a></li>
                <li{% if mm_item == 'packages' %} class="active"{% endif %}><a href="#packages">Packages</a></li>
                <li{% if mm_item == 'server' %} class="active"{% endif %}><a href="#server">Server</a></li>
                {% endcomment %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><span class="glyphicon glyphicon-user"></span> {{ request.user.username }}</a></li>
                <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span></a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>