apps/domains/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import *

urlpatterns = patterns('apps.domains.views',
    url(regex=r'^$', view='domain_list', name='all'),
    url(regex=r'^add/$', view='domain_ac', name='add_domain'),
    url(regex=r'^(?P<domain_id>\d+)/$', view='domain_ac', name='change_domain'),
    url(regex=r'^(?P<domain_id>\d+)/delete/$', view='domain_delete', name='delete_domain'),
    url(regex=r'^(?P<domain_id>\d+)/dns/$', view='domain_dns', name='dns'),
    url(regex=r'^(?P<domain_id>\d+)/dns/(?P<dns_id>\d+)/$', view='domain_dns_ac', name='change_dns'),
    url(regex=r'^(?P<domain_id>\d+)/dns/add/$', view='domain_dns_ac', name='add_dns'),
    url(regex=r'^(?P<domain_id>\d+)/dns/(?P<dns_id>\d+)/delete/$', view='domain_dns_delete', name='delete_dns'),

)

apps/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import *

urlpatterns = patterns('apps.users.views',
    url(regex=r'^$', view='user_list', name='user_list'),
    url(regex=r'^add/$', view='user_add', name='add_user'),
    #url(regex=r'^(?P<domain_id>\d+)/$', view='domain_ac', name='change_domain'),
    #url(regex=r'^(?P<domain_id>\d+)/delete/$', view='domain_delete', name='delete_domain'),
    #url(regex=r'^(?P<domain_id>\d+)/dns/$', view='domain_dns', name='dns'),
    #url(regex=r'^(?P<domain_id>\d+)/dns/(?P<dns_id>\d+)/$', view='domain_dns_ac', name='change_dns'),
    #url(regex=r'^(?P<domain_id>\d+)/dns/add/$', view='domain_dns_ac', name='add_dns'),
    #url(regex=r'^(?P<domain_id>\d+)/dns/(?P<dns_id>\d+)/delete/$', view='domain_dns_delete', name='delete_dns'),
)

lesshms/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from libs.bootstrap.forms import BootstrapAuthenticationForm


urlpatterns = patterns('',
    url(r'^$', 'apps.dashboard.views.dashboard', name='dashboard'),
)

# Auth
urlpatterns += patterns('django.contrib.auth.views', url(
    view='login',
    regex=r'^login/$',
    kwargs={
        'template_name': 'registration/login.html',
        'authentication_form': BootstrapAuthenticationForm
    },
    name='login')
)

urlpatterns += patterns('django.contrib.auth.views', url(
    view='logout',
    regex=r'^logout/$',
    kwargs={'next_page': '/'},
    name='logout'
)
)

# Apps
urlpatterns += patterns('',
    (r'^domains/', include('apps.domains.urls', namespace="domains")),
    (r'^projects/', include('apps.projects.urls', namespace="projects")),
    (r'^users/', include('apps.users.urls', namespace="users")),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

apps/users/models.py
# -*- coding: utf-8 -*-
import os
import crypt
import subprocess

from django.db import models
from django.conf import settings

from lesshms.server_conf import GID_START, UID_START, SHELL
from lesshms.paths import HOME

from lesshms.paths import CMD_USERADD, CMD_GROUPADD


class LinuxGroup(models.Model):
    name = models.CharField(u"Name", max_length=100, unique=True)
    is_system = models.BooleanField(default=False)

    class Meta:
        ordering = ["name"]

    def __unicode__(self):
        return self.name

    def gid(self):
        return str(GID_START + self.id)

    def create_system_group(self):
        if not self.is_system and not settings.DEVELOP:

            command = [CMD_GROUPADD, "-g", self.gid(), self.name]

            p = subprocess.Popen(command,
                                 bufsize=1000 * 1000,
                                 stdin=subprocess.PIPE,
                                 stderr=subprocess.PIPE,
                                 stdout=subprocess.PIPE)

            while True:
                next_line = p.stdout.readline()
                if next_line == '' and p.poll() is not None:
                    break

            self.is_system = True
            self.save()


class LinuxUser(models.Model):
    default_group = models.ForeignKey(LinuxGroup)
    username = models.CharField(u"Name", max_length=32, unique=True)

    # TODO: need salt generator
    salt = models.CharField(max_length=6, default="salt33")

    is_system = models.BooleanField(default=False)

    class Meta:
        ordering = ["username"]

    def __unicode__(self):
        return self.username

    def uid(self):
        return str(UID_START + self.id)

    def gid(self):
        return self.default_group.gid()

    def get_home_dir(self):
        return os.path.join(HOME, self.username)

    def create_system_user(self, password):
        if not self.is_system and not settings.DEVELOP:

            enc_password = crypt.crypt(password, self.salt)

            command = [
                CMD_USERADD,
                "-d", self.get_home_dir(),
                "-g", self.gid(),
                "-p", enc_password,
                "-u", self.uid(),
                "-s", SHELL,
                "--create-home",
                self.username
            ]

            p = subprocess.Popen(command,
                                 bufsize=1000 * 1000,
                                 stdin=subprocess.PIPE,
                                 stderr=subprocess.PIPE,
                                 stdout=subprocess.PIPE)

            #stdout, stderr = p.communicate()

            self.is_system = True
            self.save()
        else:
            os.makedirs(self.get_home_dir())

apps/users/forms.py
# -*- coding: utf-8 -*-

from django import forms

from apps.users.models import LinuxGroup


class NewUserForm(forms.Form):
    group = forms.ModelChoiceField(
        label=u"Group",
        required=False,
        queryset=LinuxGroup.objects.all(),
        empty_label=u"------",
        widget=forms.Select(attrs={
            "class": "form-control",
        })
    )

    create_group = forms.BooleanField(
        label=u"Create new group",
        required=False,

    )

    group_name = forms.CharField(
        label=u"New group name",
        required=False,
        max_length=32,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "disabled": "disabled",
            "placeholder": "For example, lesshms"
        }),
        help_text=u"Recommend is the same as the username."
    )

    username = forms.CharField(
        label=u"Username",
        required=True,
        max_length=32,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "For example, lesshms"
        }),
        help_text=u"The short and simple name to log on SSH."
    )

    password = forms.CharField(
        label=u"Password",
        required=True,
        max_length=32,
        widget=forms.TextInput(attrs={
            "class": "form-control"
        }),
        help_text=u"A strong password."
    )

apps/users/views.py
# -*- coding: utf-8 -*-
import time

from django.template import RequestContext
from django.template.loader import get_template
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib import messages

from apps.users.models import LinuxUser, LinuxGroup
from apps.users.forms import NewUserForm


@login_required
def user_list(request):
    users = LinuxUser.objects.all()

    template = get_template("users/user_list.html")
    context = RequestContext(request, {
        "mm_item": "users",
        "html_title": u"Linux Users",
        "users": users
    })
    return HttpResponse(template.render(context))


@login_required
def user_add(request):
    form = NewUserForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            # Group
            if form.cleaned_data["create_group"]:
                group = LinuxGroup(
                    name=form.cleaned_data["group_name"] or form.cleaned_data["username"]
                )
                group.save()

            else:
                group = form.cleaned_data["group"]
                if not group:
                    group = LinuxGroup(
                        name=form.cleaned_data["username"]
                    )
                    group.save()

            group.create_system_group()
            # TODO: Bad code, need wait group.create_system_group()
            time.sleep(2)

            # User
            if group:
                user = LinuxUser(
                    username=form.cleaned_data["username"],
                    default_group=group
                )
                user.save()
                user.create_system_user(form.cleaned_data["password"])
                messages.info(request, 'User %s is created.' % user.username)

            else:
                # TODO: Need more of a logic
                pass
            return HttpResponseRedirect(reverse("users:user_list"))

    template = get_template("users/user_add.html")
    context = RequestContext(request, {
        "mm_item": "users",
        "html_title": u"Add Linux Users",

        "form": form,

        "breadcrumbs": [
            {"name": u"Users", "url": reverse("users:user_list")},
        ],

    })
    return HttpResponse(template.render(context))

apps/users/templates/users/user_add.html
{% extends "index.html" %}

{% block application %}
    <h1>Add Linux User</h1>

    <form role="form" method="post">
        {% csrf_token %}

        <div class="row">
            <div class="col-lg-6">
                <fieldset>
                    <legend>User data</legend>
                    {% include "bootstrap/form_field.html" with field=form.username %}
                    {% include "bootstrap/form_field.html" with field=form.password %}
                </fieldset>

                <fieldset>
                    <legend>Group data</legend>
                    {% include "bootstrap/form_field.html" with field=form.group %}
                    {% include "bootstrap/checkbox_form_field.html" with field=form.create_group %}
                    {% include "bootstrap/form_field.html" with field=form.group_name %}
                </fieldset>

                <button type="submit" class="btn btn-primary">Add user</button>
            </div>
        </div>
    </form>

{% endblock %}

apps/users/templates/users/user_list.html
{% extends "index.html" %}

{% block application %}
    <div class="page-header">
        <h1>Linux users</h1>
    </div>

    {% if users %}
        <a href="{% url 'users:add_user' %}" class="btn btn-primary" style="float: right"><span class="glyphicon glyphicon-plus"></span> Add user</a>
    {% endif %}

    {% if users %}
        <table class="table table-striped">
            <colgroup>
                <col width="300px"/>
                <col width="300px"/>
                <col/>
                <col width="200px"/>
            </colgroup>
            <thead>
            <tr>
                <th>Username</th>
                <th>Group</th>
                <th>Home dir</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>
                        {{ user.username }}
                    </td>
                    <td>
                        {{ user.default_group.name }}
                    </td>
                    <td>
                        {{ user.get_home_dir }}
                    </td>
                    <td style="text-align: right">
                        {% comment %}<a href="{% url 'domains:dns' domain_id=domain.id %}" class="btn">DNS</a>
                        <a href="{% url 'domains:change_domain' domain_id=domain.id %}" class="btn"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="{% url 'domains:delete_domain' domain_id=domain.id %}" class="btn"><span class="glyphicon glyphicon-remove"></span></a>
                        {% endcomment %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <a href="{% url 'users:add_user' %}" class="btn btn-primary btn-lg">Add first user</a>
    {% endif %}

{% endblock %}