apps/domains/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import *

urlpatterns = patterns('apps.domains.views',
    url(regex=r'^$', view='domain_list', name='all'),
    url(regex=r'^add/$', view='domain_ac', name='add_domain'),
    url(regex=r'^(?P<domain_id>\d+)/$', view='domain_ac', name='change_domain'),
    url(regex=r'^(?P<domain_id>\d+)/delete/$', view='domain_delete', name='delete_domain'),
    url(regex=r'^(?P<domain_id>\d+)/dns/$', view='domain_dns', name='dns'),
    url(regex=r'^(?P<domain_id>\d+)/dns/(?P<dns_id>\d+)/$', view='domain_dns_ac', name='change_dns'),
    url(regex=r'^(?P<domain_id>\d+)/dns/add/$', view='domain_dns_ac', name='add_dns'),
    url(regex=r'^(?P<domain_id>\d+)/dns/(?P<dns_id>\d+)/delete/$', view='domain_dns_delete', name='delete_dns'),

)

apps/projects/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import *

urlpatterns = patterns('apps.projects.views',
    url(regex=r'^$', view='project_list', name='all'),
    url(regex=r'^add/$', view='project_ac', name='add_project'),
    url(regex=r'^(?P<project_id>\d+)/$', view='project_detail', name='detail'),
    url(regex=r'^(?P<project_id>\d+)/packages/$', view='project_packages', name='project_packages'),
    url(regex=r'^(?P<project_id>\d+)/nginx/$', view='project_nginx', name='project_nginx'),
    url(regex=r'^(?P<project_id>\d+)/uwsgi/$', view='project_uwsgi', name='project_uwsgi'),

    #url(regex=r'^(?P<project_id>\d+)/delete/$', view='project_delete', name='delete_project'),

    # Subrocesses
    url(regex=r'^subprocess/create_virtualenv/$', view='create_virtualenv', name='create_virtualenv'),
    url(regex=r'^subprocess/install_packages/$', view='install_packages', name='install_packages'),
    url(regex=r'^subprocess/setup_nginx/$', view='setup_nginx', name='setup_nginx'),
    url(regex=r'^subprocess/create_user/$', view='create_user', name='create_user'),

)

lesshms/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from libs.bootstrap.forms import BootstrapAuthenticationForm


urlpatterns = patterns('',
    url(r'^$', 'apps.dashboard.views.dashboard', name='dashboard'),
)

# Auth
urlpatterns += patterns('django.contrib.auth.views', url(
    view='login',
    regex=r'^login/$',
    kwargs={
        'template_name': 'registration/login.html',
        'authentication_form': BootstrapAuthenticationForm
    },
    name='login')
)

urlpatterns += patterns('django.contrib.auth.views', url(
    view='logout',
    regex=r'^logout/$',
    kwargs={'next_page': '/'},
    name='logout'
)
)

# Apps
urlpatterns += patterns('',
    (r'^domains/', include('apps.domains.urls', namespace="domains")),
    (r'^projects/', include('apps.projects.urls', namespace="projects")),
    (r'^users/', include('apps.users.urls', namespace="users")),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

apps/projects/views.py
# -*- coding: utf-8 -*-
import subprocess
import os
import json
import time

from django.shortcuts import get_object_or_404
from django.template import RequestContext
from django.template.loader import get_template
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.conf import settings

from lesshms.paths import VIRTUAL_ENV

from apps.projects.models import Project, Package
from apps.projects.forms import ProjectForm, NewPackageForm, NignxForm, UwsgiForm
from apps.users.models import LinuxUser, LinuxGroup


@login_required
def project_list(request):
    projects = Project.objects.all()

    template = get_template("projects/project_list.html")
    context = RequestContext(request, {
        "mm_item": "projects",
        "html_title": u"Projects",
        "projects": projects
    })
    return HttpResponse(template.render(context))


@login_required
def project_detail(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    template = get_template("projects/project_detail.html")
    context = RequestContext(request, {
        "mm_item": "projects",
        "dm_item": "base",
        "html_title": u"Project %s" % project.name,
        "project": project,

        "breadcrumbs": [
            {"name": u"Projects", "url": reverse("projects:all")},
        ],
    })
    return HttpResponse(template.render(context))


@login_required
def project_packages(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    packages = Package.objects.filter(project=project)

    form = NewPackageForm()

    template = get_template("projects/project_packages.html")
    context = RequestContext(request, {
        "mm_item": "projects",
        "dm_item": "packages",
        "html_title": u"Project packages",

        "project": project,
        "packages": packages,
        "form": form,

        "breadcrumbs": [
            {"name": u"Projects", "url": reverse("projects:all")},
            {"name": project.name, "url": reverse("projects:detail", kwargs={"project_id": project.id})},
        ],
    })
    return HttpResponse(template.render(context))


@login_required
def project_nginx(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    packages = Package.objects.filter(project=project)

    nginx_fields = ["nginx_port", "nginx_enable_access_log", "nginx_enable_error_log",
                    "nginx_static_root", "nginx_static_subdomain", "nginx_static_url"]

    nginx_data = {}
    for field in nginx_fields:
        nginx_data[field] = getattr(project, field)

    form = NignxForm(request.POST or nginx_data)

    if request.method == "POST":
        if form.is_valid():
            for field in nginx_fields:
                setattr(project, field, form.cleaned_data[field])

            project.save()
            project.save_nginx_config()

            messages.info(request, 'Nginx config changed.')
            return HttpResponseRedirect(reverse("projects:project_nginx", kwargs={
                "project_id": project.id
            }))

    template = get_template("projects/project_nginx.html")
    context = RequestContext(request, {
        "mm_item": "projects",
        "dm_item": "nginx",
        "html_title": u"Nginx settings",

        "project": project,
        "packages": packages,
        "form": form,

        "breadcrumbs": [
            {"name": u"Projects", "url": reverse("projects:all")},
            {"name": project.name, "url": reverse("projects:detail", kwargs={"project_id": project.id})},
        ],
    })
    return HttpResponse(template.render(context))


@login_required
def project_uwsgi(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    packages = Package.objects.filter(project=project)

    uwsgi_fields = ["uwsgi_settings_path", "uwsgi_max_requests", "uwsgi_buffer_size", "uwsgi_harakiri"]

    uwsgi_data = {}
    for field in uwsgi_fields:
        uwsgi_data[field] = getattr(project, field)

    form = UwsgiForm(request.POST or uwsgi_data)

    if request.method == "POST":
        if form.is_valid():
            for field in uwsgi_fields:
                setattr(project, field, form.cleaned_data[field])

            project.save()
            project.save_uwsgi_config()

            messages.info(request, 'Uwsgi config changed.')
            return HttpResponseRedirect(reverse("projects:project_uwsgi", kwargs={
                "project_id": project.id
            }))

    template = get_template("projects/project_uwsgi.html")
    context = RequestContext(request, {
        "mm_item": "projects",
        "dm_item": "uwsgi",
        "html_title": u"uwsgi settings",

        "project": project,
        "packages": packages,
        "form": form,

        "breadcrumbs": [
            {"name": u"Projects", "url": reverse("projects:all")},
            {"name": project.name, "url": reverse("projects:detail", kwargs={"project_id": project.id})},
        ]
    })
    return HttpResponse(template.render(context))


@login_required
def project_ac(request):

    form = ProjectForm()

    if request.method == "POST" and request.is_ajax():
        directory = Project.normalize_directory_name(request.POST.get("directory", ""))
        name = request.POST.get("name", "").strip()
        domain_id = request.POST.get("domain_id")
        user_id = request.POST.get("user_id", '')

        if directory and name:
            project = Project(
                name=name,
                directory=directory,
                domain_id=domain_id,
                user_id=user_id or None
            )

            project.save()

            data = {
                "id": project.id,
                "name": project.name,
                "directory": project.directory,
                "user_id": project.user.id if project.user else '',
                "status": "success"
            }
        else:
            data = {
                "status": "error",
                "error": u"Bad name or directory."
            }

        time.sleep(3)
        return HttpResponse(json.dumps(data), mimetype="application/json")

    template = get_template("projects/project_ac.html")
    context = RequestContext(request, {
        "mm_item": "projects",
        "html_title": u"Create project",
        "form": form,

        "breadcrumbs": [
            {"name": u"Projects", "url": reverse("projects:all")},
        ],

    })
    return HttpResponse(template.render(context))

############################
# * * * Subprocesses * * * #
############################


@login_required
def create_virtualenv(request):
    project_id = request.POST.get("project_id", None)
    project = get_object_or_404(Project, id=project_id)

    # Create virtualenv
    if not settings.DEVELOP:
        command = ["su", "-", project.user.username, "-c",  '%s %s' % (VIRTUAL_ENV, project.get_virtualenv_dir())]
    else:
        command = [VIRTUAL_ENV, project.get_virtualenv_dir()]

    p = subprocess.Popen(command,
                         bufsize=1000 * 1000,
                         stdin=subprocess.PIPE,
                         stderr=subprocess.PIPE,
                         stdout=subprocess.PIPE)

    stdout, stderr = p.communicate()

    if stderr:
        data = {
            "status": "error",
            "error": stderr
        }
    else:
        data = {
            "status": "success"
        }

    return HttpResponse(json.dumps(data), mimetype="application/json")


@login_required
def install_packages(request):
    project_id = request.POST.get("project_id", None)
    project = get_object_or_404(Project, id=project_id)

    package_name = request.POST.get("package_name", "").strip()
    package_version = request.POST.get("package_version", "").strip()

    pip = os.path.join(project.get_virtualenv_dir(), "bin/pip")

    create = upgrade = False

    try:
        package = Package.objects.get(project=project, package=package_name)
        if package.version != package_version:
            upgrade = True
    except Package.DoesNotExist:
        create = True
        package = Package(project=project)

    if (create or upgrade) and package_name and package_version:

        command = []
        if settings.DEVELOP:
            if create:
                command = [pip, "install", "%s==%s" % (package_name, package_version)]
            if upgrade:
                command = [pip, "install", "--upgrade", "%s==%s" % (package_name, package_version)]
        else:
            if create:
                command = ["su", "-", project.user.username, "-c", "%s %s %s==%s" % (
                    pip, "install", package_name, package_version)]
            if upgrade:
                command = ["su", "-", project.user.username, "-c", "%s %s %s %s==%s" % (
                    pip, "install", "--upgrade", package_name, package_version)]

        p = subprocess.Popen(command,
                             bufsize=1000 * 1000,
                             stdin=subprocess.PIPE,
                             stderr=subprocess.PIPE,
                             stdout=subprocess.PIPE)
        stdout, stderr = p.communicate()

        package.package = package_name
        package.version = package_version
        package.save()

    return HttpResponse(json.dumps(""), mimetype="application/json")


@login_required
def setup_nginx(request):
    project_id = request.POST.get("project_id", None)
    project = get_object_or_404(Project, id=project_id)

    project.save_nginx_config()

    time.sleep(3)
    return HttpResponse(json.dumps(""), mimetype="application/json")


@login_required
def create_user(request):
    project_id = request.POST.get("project_id", None)
    project = get_object_or_404(Project, id=project_id)

    username = request.POST.get("username", "")
    password = request.POST.get("password", "")

apps/projects/templates/projects/progress.html
<!-- Modal -->
<div class="modal fade" id="processModal" tabindex="-1" role="dialog" aria-labelledby="processModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Create project</h4>
            </div>
            <div class="modal-body">
                <h3 class="progress-title"></h3>
                <div class="alert alert-danger" style="display: none"></div>

                <div class="progress progress-striped active">
                    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                        <span class="sr-only">60% Complete</span>
                    </div>
                </div>

                <div class="time-left"></div>

            </div>
            <div class="modal-footer">
                <button type="button"  data-dismiss="modal" class="btn btn-primary disabled" id="progress-close">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

apps/projects/templates/projects/project_ac.html
{% extends "index.html" %}{% load static %}

{% block js %}
    <script>
        var REDIRECT_TO = 'project';
    </script>
{% endblock %}

{% block application %}
    <h1>Create project</h1>

    <form role="form" method="post">
        {% csrf_token %}

        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-8">
                <h3>Base parameters</h3>
                <fieldset>
                    <legend>Base</legend>
                    {% include "bootstrap/form_field.html" with field=form.name %}
                    {% include "bootstrap/form_field.html" with field=form.directory %}
                    {% include "bootstrap/form_field.html" with field=form.domain %}

                </fieldset>

                <fieldset>
                    <legend>Linux User for access</legend>
                    {% include "bootstrap/form_field.html" with field=form.user %}
                    {% include "bootstrap/checkbox_form_field.html" with field=form.create_user %}
                    {% include "bootstrap/form_field.html" with field=form.username %}
                    {% include "bootstrap/form_field.html" with field=form.password %}

                </fieldset>

            </div>
            <div class="col-xs-6 col-sm-6 col-md-4">
                <h3>Preset packages</h3>
                {% include "bootstrap/form_field.html" with field=form.django_version %}
                {% include "bootstrap/form_field.html" with field=form.south_version %}
                {% include "bootstrap/form_field.html" with field=form.pil_version %}

            </div>
        </div>

        <button id="save_project" type="submit" class="btn btn-primary">Create project</button>
    </form>

    {% include "projects/progress.html" %}

    <div class="var" id="project_id"></div>

{% endblock %}

{% block ex_js %}
    <script src="{% get_static_prefix %}js/vendor/ajaxq.js"></script>
{% endblock %}

apps/projects/templates/projects/project_detail.html
{% extends "index.html" %}

{% block application %}
    <div class="page-header">
        <h1>Project {{ project.name }}</h1>
    </div>

    <ul class="nav nav-tabs project-nav">
        <li{% if dm_item == "base" %} class="active"{% endif %}><a href="{% url 'projects:detail' project_id=project.id %}">Base</a></li>
        <li{% if dm_item == "nginx" %} class="active"{% endif %}><a href="{% url 'projects:project_nginx' project_id=project.id %}">Nginx</a></li>
        <li{% if dm_item == "uwsgi" %} class="active"{% endif %}><a href="{% url 'projects:project_uwsgi' project_id=project.id %}">Uwsgi</a></li>
        <li{% if dm_item == "packages" %} class="active"{% endif %}><a href="{% url 'projects:project_packages' project_id=project.id %}">Packages</a></li>
    </ul>

    {% block content %}
        <table class="table table-striped">
            <colgroup>
                <col width="200px"/>
                <col/>
            </colgroup>
            <thead>
                <tr>
                    <th>Param</th>
                    <th>Value</th>
                </tr>
            </thead>

            <tbody>

            <tr class="success">
                <td colspan="2">Basic</td>
            </tr>

            <tr>
                <td>Domain</td>
                <td>{{ project.domain.get_normal_name }}</td>
            </tr>

            <tr>
                <td>Project user</td>
                <td>{{ project.user.username }}</td>
            </tr>

            <tr>
                <td>Project path</td>
                <td>{{ project.get_project_root }}</td>
            </tr>

            <tr>
                <td>Virtualenv</td>
                <td>{{ project.get_virtualenv_dir }}</td>
            </tr>

            <tr class="success">
                <td colspan="2">UWSGI</td>
            </tr>

            <tr>
                <td>Conf</td>
                <td>{{ project.get_uwsgi_conf }}</td>
            </tr>

            <tr>
                <td>Socket</td>
                <td>{{ project.get_sock_path_for_uwsgi }}</td>
            </tr>

            <tr>
                <td>Touch</td>
                <td>{{ project.get_uwsgi_touch }}</td>
            </tr>

            <tr class="success">
                <td colspan="2">NGINX</td>
            </tr>

            <tr>
                <td>Domain</td>
                <td>{{ project.get_nginx_conf }}</td>
            </tr>

            </tbody>
        </table>
    {% endblock %}

{% endblock %}

apps/projects/templates/projects/project_list.html
{% extends "index.html" %}

{% block application %}
    <div class="page-header">
        <h1>Projects</h1>
    </div>

    {% if projects %}
        <a href="{% url 'projects:add_project' %}" class="btn btn-primary" style="float: right"><span class="glyphicon glyphicon-plus"></span> Add project</a>
    {% endif %}

    {% if projects %}
        <table class="table table-striped">
            <colgroup>
                <col width="300px"/>
                <col width="150px"/>
                <col/>
                <col width="200px"/>
            </colgroup>
            <thead>
            <tr>
                <th>Project name</th>
                <th>Domain</th>
                <th>User</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for project in projects %}
                <tr>
                    <td>
                        <a href="{% url 'projects:detail' project_id=project.id %}">{{ project.name }}</a>
                    </td>
                    <td>
                        {{ project.domain.get_normal_name }}
                    </td>
                    <td>
                        {% if project.user %}{{ project.user.username }}{% endif %}
                    </td>
                    <td style="text-align: right">
                        {% comment %}<a href="{% url 'domains:dns' domain_id=domain.id %}" class="btn">DNS</a>
                        <a href="{% url 'domains:change_domain' domain_id=domain.id %}" class="btn"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="{% url 'domains:delete_domain' domain_id=domain.id %}" class="btn"><span class="glyphicon glyphicon-remove"></span></a>
                        {% endcomment %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <a href="{% url 'projects:add_project' %}" class="btn btn-primary btn-lg">Add first project</a>
    {% endif %}

{% endblock %}

apps/projects/templates/projects/project_nginx.html
{% extends "projects/project_detail.html" %}{% load static %}

{% block content %}


    <form role="form" method="post">
        {% csrf_token %}

        <div class="row">
            <div class="col-lg-6">

            {% include "bootstrap/form_field.html" with field=form.nginx_port %}

            <fieldset>
                <legend>Logs</legend>
                {% include "bootstrap/checkbox_form_field.html" with field=form.nginx_enable_access_log %}
                {% include "bootstrap/checkbox_form_field.html" with field=form.nginx_enable_error_log %}
            </fieldset>

            <fieldset>
                <legend>Static</legend>

                {% include "bootstrap/form_field.html" with field=form.nginx_static_root %}
                {% include "bootstrap/form_field.html" with field=form.nginx_static_subdomain %}
                {% include "bootstrap/form_field.html" with field=form.nginx_static_url %}
            </fieldset>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Save</button>

    </form>




{% endblock %}

apps/projects/templates/projects/project_packages.html
{% extends "projects/project_detail.html" %}{% load static %}

{% block js %}
    <script>
        var REDIRECT_TO = 'packages';
    </script>
{% endblock %}

{% block content %}

    <a href="#" id="add_package_buttom" class="btn btn-primary">Add package</a>


    <div style="clear: both"></div>

    <h3>Packages</h3>

    {% if packages %}
        <table class="table table-striped">
            <colgroup>
                <col width="400px"/>
                <col/>
                <col width="200px"/>
            </colgroup>
            <thead>
            <tr>
                <th>Package</th>
                <th>Version</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for package in packages %}
                <tr>
                    <td>
                        {{ package.package }}
                    </td>
                    <td>
                        {{ package.version }}
                    </td>
                    <td style="text-align: right">
                        {% comment %}<a href="#" class="btn"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="#" class="btn"><span class="glyphicon glyphicon-remove"></span></a>{% endcomment %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}

    {% endif %}

    <!-- Modal -->

    <div class="modal fade" id="addPackageModal" tabindex="-1" role="dialog" aria-labelledby="addPackageModalLabel" aria-hidden="true">
        <form role="form" method="post">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add package</h4>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    {% include "bootstrap/form_field.html" with field=form.package %}
                    {% include "bootstrap/form_field.html" with field=form.version %}
                </div>
                <div class="modal-footer">
                    <button type="submit" id="add_package" class="btn btn-primary">Add package</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
        </form>
    </div><!-- /.modal -->

    <div class="var" id="project_id">{{ project.id }}</div>

    {% include "projects/progress.html" %}

{% endblock %}

{% block ex_js %}
    <script src="{% get_static_prefix %}js/vendor/ajaxq.js"></script>
{% endblock %}

apps/projects/templates/projects/project_uwsgi.html
{% extends "projects/project_detail.html" %}{% load static %}

{% block content %}


    <form role="form" method="post">
        {% csrf_token %}

        <div class="row">
            <div class="col-lg-6">

            {% include "bootstrap/form_field.html" with field=form.uwsgi_settings_path %}
            {% include "bootstrap/form_field.html" with field=form.uwsgi_max_requests %}
            {% include "bootstrap/form_field.html" with field=form.uwsgi_buffer_size %}
            {% include "bootstrap/form_field.html" with field=form.uwsgi_harakiri %}

            </div>
        </div>

        <button type="submit" class="btn btn-primary">Save</button>

    </form>




{% endblock %}